pipelines:
  lambda.instance-control:
    group: lambda
    label_template: "${COUNT}"
    materials:
      lambda.instance-control:
        git: https://github.com/ukparliament/lambda-instance-control.git
        branch: master
        auto_update: true
    stages:
      - test:
          jobs:
            build:
              tasks:
                - exec:
                    run_if: passed
                    command: make
                    arguments:
                      - test
      - deploy:
          jobs:
            deploy:
              tasks:
                - exec:
                    run_if: passed
                    command: make
                    arguments:
                      - deploy

environments:
  Web.DEVCI:
    pipelines:
      - lambda.instance-control