pipelines:
  instance.control:
    group: lambdas
    label_template: "${COUNT}"
    materials:
      instance.control-git:
        git: git@github.com:ukparliament/lambda-instance-control.git
        branch: master
        auto_update: true
    stages:
      - deploy:
          jobs:
            deploy:
              tasks:
                - exec:
                    run_if: passed
                    command: make
                    arguments:
                      - deploy

environments:
  Web.DEVCI:
    pipelines:
      - lambda-instance-control